import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	sidebar: [
		{
			type: 'category',
			label: 'General',
			items: ['General/Welcome'],
			collapsed: false
		},
		{
			type: 'category',
			label: 'Guide',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'Guide'
				}
			]
		},
		{
			type: 'category',
			label: 'Documentation',
			collapsed: true,
			items: [
				{
					type: 'category',
					link: {
						type: 'doc',
						id: 'Documentation/api-framework/index'
					},
					label: '@sapphire/framework',
					items: require('./docs/Documentation/api-framework/typedoc-sidebar.cjs')
				},
				{
					type: 'category',
					link: {
						type: 'doc',
						id: 'Documentation/api-pieces/index'
					},
					label: '@sapphire/pieces',
					items: require('./docs/Documentation/api-pieces/typedoc-sidebar.cjs')
				},
				{
					type: 'category',
					link: {
						type: 'doc',
						id: 'Documentation/api-utilities/index'
					},
					label: 'Sapphire Utilities',
					items: require('./docs/Documentation/api-utilities/typedoc-sidebar.cjs')
				},
				{
					type: 'category',
					link: {
						type: 'doc',
						id: 'Documentation/api-plugins/index'
					},
					label: 'Sapphire Plugins',
					items: require('./docs/Documentation/api-plugins/typedoc-sidebar.cjs')
				},
				{
					type: 'category',
					link: {
						type: 'doc',
						id: 'Documentation/api-type/index'
					},
					label: '@sapphire/type',
					items: require('./docs/Documentation/api-type/typedoc-sidebar.cjs')
				},
				{
					type: 'category',
					link: {
						type: 'doc',
						id: 'Documentation/api-shapeshift/index'
					},
					label: '@sapphire/shapeshift',
					items: require('./docs/Documentation/api-shapeshift/typedoc-sidebar.cjs')
				}
			]
		}
	]
};

export default sidebars;
