module.exports = {
	sidebar: [
		{
			type: 'category',
			label: 'General',
			items: ['General/Welcome'],
			collapsed: false
		},
		{
			type: 'category',
			label: 'Guide',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'Guide'
				}
			]
		},
		{
			type: 'category',
			label: 'Documentation',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'Documentation'
				}
			]
		}
	]
};
